version: "2"

services:
  api:
    build:
      context: ./backend/
    container_name: hyf_backend
    depends_on:
      - store
    volumes:
      - ./backend/src:/hyf/src
      - ./_volumes:/hyf/uploads
    environment:
      APP_VERSION_NUMBER:
      APP_VERSION_LABEL:
      PG_CONNECTION_STRING: postgres://admin:admin@store:5432/emojipoetry
      # PG_CONNECTION_STRING: postgres://admin:admin@142.93.51.96:5432/emojipoetry
      DOMAIN:

  store:
    image: postgres
    container_name: hyf_store
    build:
      context: ./store
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DATABASE: emojipoetry
    volumes:
      - ./store:/var/lib/postgresql
      - ./_volumes/store-behaviourkit:/var/lib/postgresql/data

